### ISSUE TITLE
Add Coffee Asset Tracking app to repository

### ISSUE THREAD

**Issue by truedat101** [IoTone/BlockchainInABox#10]
We should fork from / make a submodule of https://github.com/IoTone/substrate-enterprise-sample-v3/issues

and add to this repository and build up the architecture outlined in #8

**Comment by Damfortx8** [comment]
![image](https://user-images.githubusercontent.com/92606981/143256434-34b23801-8354-4f0e-8085-537ddcb830d1.png)

**Comment by truedat101** [comment]
I'll make a fork.

**Comment by truedat101** [comment]
Everything is here: https://github.com/IoTone/substrate-coffee-supplychain

**Comment by truedat101** [comment]
BTW it's not a fork, I just cloned it.  If you'd like to continue to main and merge back upstream, add this to your .git/config

```
[remote "upstream"]
	url = git@github.com:IoTone/substrate-enterprise-sample-v3.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
```
